FROM python:3.11
# FROM debian:bookworm-slim
ARG TARGETPLATFORM
WORKDIR /app
COPY ./requirements-omar.txt /app
COPY ./requirements-pi2.txt /app
RUN apt-get update && apt-get upgrade
RUN apt-get install python3-pip -y
RUN pip install --upgrade pip
RUN if [ "$TARGETPLATFORM" = "linux/arm/v8" ]; then \
	# apt install -y python3-libcamera python3-kms++ && \
	# apt install -y python3-prctl libatlas-base-dev ffmpeg libopenjp2-7 python3-pip && \
	apt install -y ffmpeg libsm6 libcap-dev libxext6 libavformat-dev libavcodec-dev libavdevice-dev libavutil-dev libavfilter-dev libswscale-dev libswresample-dev pkg-config && \
	apt install -y python3-numpy &&\
	apt install -y python3-picamera2 --no-install-recommends;\
	#apt install -y python3-picamera2 ; \
fi	
RUN if [ "$TARGETPLATFORM" = "linux/arm64/v8" ]; then \
        echo "Running on ARM64 (v8), installing ARM-specific requirements"; \
        pip3 install -r requirements-omar.txt && \
        apt-get install -y ffmpeg libsm6 libxext6; \
    elif [ "$TARGETPLATFORM" = "linux/arm/v8" ]; then \
        echo "Running arm/v8 specific stuff for the pi"; \
        pip install -r requirements-pi2.txt; \
    fi
COPY . .
EXPOSE 5000 
CMD ["python", "app.py", "--host", "0.0.0.0"]
